services:
  web:
    build: .
    env_file:
      - .env
    environment:
      COOKIE_SECURE: "${COOKIE_SECURE:-false}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "0.0.0.0:8805:8000"
